### PR TITLE
Generate Api Types - Initial Implementation

### PR DESCRIPTION
**Pull request by ricklove**
This is an initial implementation of the contract type generator:

Preview of results here: https://github.com/ricklove/minter-sdk/tree/rick/generate-api-types/contracts/types

### Quick Comparison:

- left: manually written (https://github.com/ricklove/minter-sdk/blob/rick/generate-api-types/contracts/src/auction-interface.ts)
- right: generated (https://github.com/ricklove/minter-sdk/blob/rick/generate-api-types/contracts/types/english_auction_tez.ts)

image

### Usage

How would this be used?

Here is an initial ideal of how this would be used. (Still in the process of refining this to make it as minimal as possible while still retaining strict type safety):

https://github.com/ricklove/minter-sdk/blob/rick/generate-api-types/packages/contract-api-generator/src/example-usage.ts

```ts
    const contract = await Tezos.contract.at(``);
    contract.methods.bid(tas.nat(0));
    contract.methods.configure({
        asset: [{
            fa2_address: tas.address(`tz123`),
            fa2_batch: [{
                amount: tas.nat(100),
                token_id: tas.nat(`100000000000000`),
            }],
        }],
        start_time: tas.timestamp(new Date()),
        end_time: tas.timestamp(`2020-01-01`),
        extend_time: tas.nat(10),
        min_raise: tas.mutez(10),
        min_raise_percent: tas.nat(10),
        opening_price: tas.mutez(10),
        round_time: tas.nat(10),
    });
```

image

### Notes

You can run with: `yarn run generate-api`

There is no need to run the sandbox, as this uses the `.tz` files that are already compiled.

This also includes a prototype of multiple project improvements:

- tsconfig updated
- eslint setup with developer performance focused rules
- yarn workspaces

This also has the beginning of a cli, which would be called like this:

`minter-cli --g ./contracts/bin ./contracts/types`

### CODE REVIEW

**Comment by emmanueldenloye** [comment]
It seems like if this PR goes through (I don't see any reason why not.... to be sure) that this should close issue #20? Do you agree @ricklove

**Comment by ricklove** [comment]
@emmanueldenloye looks like that is the issue yeah.

**Comment by ricklove** [comment]
Reverted changes to contract/src and contract/test files (which were due to eslint updates)

**Comment by ricklove** [comment]
Added description about usage.

**Comment by ricklove** [comment]
This was moved to `taquito` repo

**Pull request closed without merging**
